[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

# Compiler settings
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing settings
gas_reports = ["*"]
gas_limit = 30_000_000

# Deployment settings
# eth_rpc_url = "${ETH_RPC_URL}"
# private_key = "${PRIVATE_KEY}"

# Additional settings for better development experience
auto_detect_solc = false
bytecode_hash = "none"
cbor_metadata = false

[rpc_endpoints]
anvil = "http://localhost:8545"
sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"
mainnet = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"

# [etherscan]
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
